# Generated by Django 4.2.16 on 2024-09-14 05:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(null=True, upload_to=core.models.employee_image_file_path),
        ),
    ]
